baseURL = 'https://dongranzhai.github.io/doris-web/'
title = 'Dongran Zhai'
theme = "hugo-coder"

languageCode = 'us-cn'
defaultContentLanguage = "us"
paginate = 6
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Dongran Zhai"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Dongran's personal website"
keywords = "About,Research,Papers,Contact"
info = ["PhD Candidate","Ocean and Climate Data Science","University of California, Santa Cruz"]
# ["Detection & attribution","Ocean chlorophyll","Bayesian heirarchical model"]
# bio = ["Hi, I am "]
avatarURL = "images/avatar.JPG"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/DongranZhai"


[[params.social]]
name = "Googlescholar"
icon = "fa-brands fa-google-scholar fa-2x"
weight = 2
url = "https://scholar.google.com/citations?user=2O8Mr0oAAAAJ&hl=zh-CN"


[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/dongran-zhai-20aa99155/"



[languages.us]
languageName = ":us:"

[[languages.us.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.us.menu.main]]
name = "Research"
weight = 2
url = "research/"

[[languages.us.menu.main]]
name = "Publications"
weight = 3
url = "publications/"

[[languages.us.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[languages.cn]
languageName = ":cn:"
title = "翟东冉"

[languages.cn.params]
author = "Dongran Zhai"
info = "Climate and Ocean Data Analyst"
description = ""
keywords = ""

[[languages.cn.menu.main]]
name = "关于我"
weight = 1
url = "about/"

[[languages.cn.menu.main]]
name = "研究"
weight = 2
url = "research/"

[[languages.cn.menu.main]]
name = "发表"
weight = 3
url = "publications/"

[[languages.cn.menu.main]]
name = "联系我"
weight = 5
url = "contact/"
